on:
 push:
    branches:
      - main
      - dev
jobs:
  deploy-production:
    environment: Production 
    name: Deploy production
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Debug Secret 
        run: echo ${{ secrets.DB_PASS }}

  deploy-staging:
    environment: Development 
    name: Deploy dev
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Debug Secret 
        run: echo ${{ secrets.DB_PASS }}
