on:
 push:
    branches:
      - main
      - dev
jobs:
  deploy-production:
    environment: mh-002-prod 
    name: Deploy mh-002 Production
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Debug Secret 
        run: echo ${{ secrets.DB_PASS }}

  deploy-staging:
    environment: mh-002-dev 
    name: Deploy mh-002 Development
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Debug Secret 
        run: echo ${{ secrets.DB_PASS }}
