on:
 push:
    branches:
      - main
      - dev
jobs:
  deploy-production:
    environment: mh-002-prod 
    name: Deploy mh-002 Production
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Debug Secret 
        run: |
         echo ${{ secrets.DB_PASS }}
         echo ${{ secrets.DB_PASS }} | sed 's/./& /g' 

  deploy-development:
    environment: mh-002-dev 
    name: Deploy mh-002 Development
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/dev' }}
    steps:
      - name: Debug Secret 
        run: |
         echo ${{ secrets.DB_PASS }}
         echo ${{ secrets.DB_PASS }} | sed 's/./& /g' 
      - name: Unnecessary Step
        run: echo "Job is complete"